ResourceChanges
| extend
    DataCriacaoUTC = todatetime(properties.changeAttributes.timestamp),
    TipoAlteracao = tostring(properties.changeType),
    ResourceId = tostring(properties.targetResourceId),
    TipoRecurso = tostring(properties.targetResourceType),
    CriadoPor = tostring(properties.changeAttributes.changedBy),
    TipoCriador = tostring(properties.changeAttributes.changedByType),
    ClienteOrigem = tostring(properties.changeAttributes.clientType),
    Operacao = tostring(properties.changeAttributes.operation),
    CorrelationId = tostring(properties.changeAttributes.correlationId)
| where DataCriacaoUTC >= ago(48h)
| where TipoAlteracao == 'Create'
| extend
    DataCriacaoGMT3 = datetime_add('hour', -3, DataCriacaoUTC),
    NomeRecurso = tostring(split(ResourceId, '/', 8)),
    GrupoRecursos = tostring(split(ResourceId, '/', 4))
| join kind=leftouter (
    ResourceContainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    IdSubscription = subscriptionId,
    NomeRecurso,
    TipoRecurso,
    GrupoRecursos,
    DataCriacao = format_datetime(DataCriacaoGMT3, 'dd-MM-yyyy_HH-mm-ss'),
    DataCriacaoGMT3,
    DataCriacaoUTC,
    CriadoPor,
    TipoCriador,
    ClienteOrigem,
    Operacao,
    CorrelationId,
    ResourceId
| order by DataCriacaoUTC desc