Resources
| summarize
    QuantidadeRecursos = count(),
    QuantidadeResourceGroups = dcount(resourceGroup),
    QuantidadeLocalizacoes = dcount(location)
    by subscriptionId, TipoRecurso = type
| join kind=leftouter (
    ResourceContainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    IdSubscription = subscriptionId,
    TipoRecurso,
    QuantidadeRecursos,
    QuantidadeResourceGroups,
    QuantidadeLocalizacoes
| order by NomeSubscription asc, QuantidadeRecursos desc, TipoRecurso asc