Resources
| extend
    TagBU = tostring(tags['BU']),
    TagCC = tostring(tags['CC']),
    TagAMBIENTE = tostring(tags['AMBIENTE']),
    TagCLIENTE = tostring(tags['CLIENTE']),
    TagCCOWNER = tostring(tags['CCOWNER'])
| where
    isempty(TagBU)
    or isempty(TagCC)
    or isempty(TagAMBIENTE)
    or isempty(TagCLIENTE)
    or isempty(TagCCOWNER)
| join kind=leftouter (
    ResourceContainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    IdSubscription = subscriptionId,
    NomeRecurso = name,
    TipoRecurso = type,
    GrupoRecursos = resourceGroup,
    Localizacao = location,
    BUAusente = isempty(TagBU),
    CCAusente = isempty(TagCC),
    AmbienteAusente = isempty(TagAMBIENTE),
    ClienteAusente = isempty(TagCLIENTE),
    CCOwnerAusente = isempty(TagCCOWNER),
    TagBU,
    TagCC,
    TagAMBIENTE,
    TagCLIENTE,
    TagCCOWNER,
    ResourceId = id
| order by NomeSubscription asc, TipoRecurso asc, NomeRecurso asc