Resources
| extend
    CC = tostring(tags['CC']),
    AMBIENTE = tostring(tags['AMBIENTE']),
    CLIENTE = tostring(tags['CLIENTE']),
    CCOWNER = tostring(tags['CCOWNER']),
    CAPEX = tostring(tags['CAPEX']),
    DISPONIBILIDADE = tostring(tags['DISPONIBILIDADE']),
    BU = tostring(tags['BU']),
    DOMINIO = tostring(tags['DOMINIO']),
    ENDOFLIFE = tostring(tags['ENDOFLIFE']),
    FUNCAO = tostring(tags['FUNCAO']),
    PRODUTO = tostring(tags['PRODUTO']),
    RESERVA = tostring(tags['RESERVA']),
    BACKUP = tostring(tags['BACKUP']),
    START = tostring(tags['START']),
    SQUAD = tostring(tags['SQUAD']),
    STOP = tostring(tags['STOP']),
    WAVE = tostring(tags['WAVE']),
    SO = tostring(tags['SO'])
| extend
    QuantidadeTagsPadraoPreenchidas =
        iff(isnotempty(CC), 1, 0) +
        iff(isnotempty(AMBIENTE), 1, 0) +
        iff(isnotempty(CLIENTE), 1, 0) +
        iff(isnotempty(CCOWNER), 1, 0) +
        iff(isnotempty(CAPEX), 1, 0) +
        iff(isnotempty(DISPONIBILIDADE), 1, 0) +
        iff(isnotempty(BU), 1, 0) +
        iff(isnotempty(DOMINIO), 1, 0) +
        iff(isnotempty(ENDOFLIFE), 1, 0) +
        iff(isnotempty(FUNCAO), 1, 0) +
        iff(isnotempty(PRODUTO), 1, 0) +
        iff(isnotempty(RESERVA), 1, 0) +
        iff(isnotempty(BACKUP), 1, 0) +
        iff(isnotempty(START), 1, 0) +
        iff(isnotempty(SQUAD), 1, 0) +
        iff(isnotempty(STOP), 1, 0) +
        iff(isnotempty(WAVE), 1, 0) +
        iff(isnotempty(SO), 1, 0)
| join kind=leftouter (
    ResourceContainers
    | where type =~ 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    subscriptionId,
    resourceGroup,
    NomeRecurso = name,
    TipoRecurso = type,
    Localizacao = location,
    CC,
    AMBIENTE,
    CLIENTE,
    CCOWNER,
    CAPEX,
    DISPONIBILIDADE,
    BU,
    DOMINIO,
    ENDOFLIFE,
    FUNCAO,
    PRODUTO,
    RESERVA,
    BACKUP,
    START,
    SQUAD,
    STOP,
    WAVE,
    SO,
    QuantidadeTagsPadraoPreenchidas,
    ResourceId = id
| order by NomeSubscription asc, resourceGroup asc, NomeRecurso asc
