Resources
| project
    subscriptionId,
    resourceGroup,
    name,
    type,
    location,
    kind,
    sku,
    zones,
    managedBy,
    identity,
    plan,
    extendedLocation,
    tags,
    properties,
    id
| join kind=leftouter (
    ResourceContainers
    | where type =~ 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    subscriptionId,
    NomeRecurso = name,
    TipoRecurso = type,
    GrupoRecursos = resourceGroup,
    Localizacao = location,
    Kind = kind,
    SKU = sku,
    Zonas = zones,
    GerenciadoPor = managedBy,
    Identidade = identity,
    Plano = plan,
    LocalizacaoEstendida = extendedLocation,
    Tags = tags,
    Propriedades = properties,
    ResourceId = id
| order by NomeSubscription asc, TipoRecurso asc, NomeRecurso asc
