Resources
| extend
    TagAMBIENTE = tostring(tags['AMBIENTE']),
    TagBACKUP = tostring(tags['BACKUP']),
    TagBU = tostring(tags['BU']),
    TagCAPEX = tostring(tags['CAPEX']),
    TagCC = tostring(tags['CC']),
    TagCCOWNER = tostring(tags['CCOWNER']),
    TagCLIENTE = tostring(tags['CLIENTE']),
    TagDISPONIBILIDADE = tostring(tags['DISPONIBILIDADE']),
    TagDOMINIO = tostring(tags['DOMINIO']),
    TagENDOFLIFE = tostring(tags['ENDOFLIFE']),
    TagFUNCAO = tostring(tags['FUNCAO']),
    TagPRODUTO = tostring(tags['PRODUTO']),
    TagRESERVA = tostring(tags['RESERVA']),
    TagSO = tostring(tags['SO']),
    TagSQUAD = tostring(tags['SQUAD']),
    TagSTART = tostring(tags['START']),
    TagSTOP = tostring(tags['STOP']),
    TagWAVE = tostring(tags['WAVE'])
| join kind=leftouter (
    ResourceContainers
    | where type == 'microsoft.resources/subscriptions'
    | project subscriptionId, NomeSubscription = name
) on subscriptionId
| project-away subscriptionId1
| project
    NomeSubscription,
    IdSubscription = subscriptionId,
    NomeRecurso = name,
    TipoRecurso = type,
    GrupoRecursos = resourceGroup,
    Localizacao = location,
    Kind = kind,
    GerenciadoPor = managedBy,
    SkuNome = tostring(sku.name),
    SkuTier = tostring(sku.tier),
    EstadoProvisionamento = tostring(properties.provisioningState),
    DataCriacaoUTC = tostring(properties.timeCreated),
    TagAMBIENTE,
    TagBACKUP,
    TagBU,
    TagCAPEX,
    TagCC,
    TagCCOWNER,
    TagCLIENTE,
    TagDISPONIBILIDADE,
    TagDOMINIO,
    TagENDOFLIFE,
    TagFUNCAO,
    TagPRODUTO,
    TagRESERVA,
    TagSO,
    TagSQUAD,
    TagSTART,
    TagSTOP,
    TagWAVE,
    ResourceId = id
| order by NomeSubscription asc, TagBU asc, TipoRecurso asc, NomeRecurso asc